export const movies = [
  {
    popularity: 8.5,
    release_date: '2023-07-21',
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    vote_average: 8.3,
    vote_count: 5420,
    duration: 180,
    situation: 'released',
    budget: 100000000,
    revenue: 952000000,
    profit: 852000000,
    sinopsis:
      'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    genre: 'Biography, Drama, History',
  },
  {
    popularity: 9.2,
    release_date: '2023-07-19',
    title: 'Barbie',
    original_title: 'Barbie',
    vote_average: 7.1,
    vote_count: 6890,
    duration: 114,
    situation: 'released',
    budget: 145000000,
    revenue: 1445000000,
    profit: 1300000000,
    sinopsis:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    genre: 'Adventure, Comedy, Fantasy',
  },
  {
    popularity: 7.8,
    release_date: '2024-03-15',
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    vote_average: 8.7,
    vote_count: 4320,
    duration: 166,
    situation: 'released',
    budget: 190000000,
    revenue: 711000000,
    profit: 521000000,
    sinopsis:
      'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future only he can foresee.',
    genre: 'Science Fiction, Adventure',
  },
  {
    popularity: 6.9,
    release_date: '2023-11-22',
    title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    vote_average: 7.4,
    vote_count: 3210,
    duration: 157,
    situation: 'released',
    budget: 100000000,
    revenue: 337000000,
    profit: 237000000,
    sinopsis:
      'Years before he would become the tyrannical President of Panem, 18-year-old Coriolanus Snow is the last hope for his fading lineage. With the 10th annual Hunger Games fast approaching, the young Snow is assigned to mentor Lucy Gray Baird.',
    genre: 'Action, Adventure, Drama',
  },
  {
    popularity: 8.1,
    release_date: '2024-05-24',
    title: 'Furiosa: A Mad Max Saga',
    original_title: 'Furiosa: A Mad Max Saga',
    vote_average: 7.9,
    vote_count: 2890,
    duration: 148,
    situation: 'released',
    budget: 168000000,
    revenue: 173000000,
    profit: 5000000,
    sinopsis:
      'The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max in Fury Road.',
    genre: 'Action, Adventure, Science Fiction',
  },
  {
    popularity: 7.3,
    release_date: '2023-10-06',
    title: 'The Creator',
    original_title: 'The Creator',
    vote_average: 7.1,
    vote_count: 2540,
    duration: 133,
    situation: 'released',
    budget: 80000000,
    revenue: 104000000,
    profit: 24000000,
    sinopsis:
      'Amid a future war between the human race and the forces of artificial intelligence, Joshua, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI.',
    genre: 'Science Fiction, Action, Thriller',
  },
  {
    popularity: 9.5,
    release_date: '2025-05-02',
    title: 'Avengers: Secret Wars',
    original_title: 'Avengers: Secret Wars',
    vote_average: 0,
    vote_count: 0,
    duration: 0,
    situation: 'upcoming',
    budget: 400000000,
    revenue: 0,
    profit: 0,
    sinopsis:
      'The Avengers face their most dangerous challenge yet as multiple realities collide in an epic battle that will determine the fate of the multiverse.',
    genre: 'Action, Adventure, Science Fiction',
  },
  {
    popularity: 6.7,
    release_date: '2023-09-15',
    title: 'A Haunting in Venice',
    original_title: 'A Haunting in Venice',
    vote_average: 6.8,
    vote_count: 1890,
    duration: 103,
    situation: 'released',
    budget: 60000000,
    revenue: 122000000,
    profit: 62000000,
    sinopsis:
      'In post-World War II Venice, Poirot, now retired and living in his own exile, reluctantly attends a seance. But when one of the guests is murdered, it is up to the former detective to once again uncover the killer.',
    genre: 'Mystery, Thriller, Crime',
  },
  {
    popularity: 8.9,
    release_date: '2024-06-14',
    title: 'Inside Out 2',
    original_title: 'Inside Out 2',
    vote_average: 7.6,
    vote_count: 5670,
    duration: 96,
    situation: 'released',
    budget: 200000000,
    revenue: 1698000000,
    profit: 1498000000,
    sinopsis:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren't sure how to feel when Anxiety shows up.",
    genre: 'Animation, Family, Adventure',
  },
  {
    popularity: 7.5,
    release_date: '2024-02-16',
    title: 'Madame Web',
    original_title: 'Madame Web',
    vote_average: 5.4,
    vote_count: 2340,
    duration: 116,
    situation: 'released',
    budget: 80000000,
    revenue: 100000000,
    profit: 20000000,
    sinopsis:
      'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women bound for powerful destinies...if they can all survive a deadly present.',
    genre: 'Action, Science Fiction',
  },
  {
    popularity: 8.3,
    release_date: '2025-07-25',
    title: 'Mission: Impossible - The Final Reckoning',
    original_title: 'Mission: Impossible - The Final Reckoning',
    vote_average: 0,
    vote_count: 0,
    duration: 0,
    situation: 'upcoming',
    budget: 291000000,
    revenue: 0,
    profit: 0,
    sinopsis:
      'Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity if it falls into the wrong hands. With control of the future and the fate of the world at stake, a deadly race around the globe begins.',
    genre: 'Action, Thriller, Adventure',
  },
  {
    popularity: 6.4,
    release_date: '2023-12-15',
    title: 'Wonka',
    original_title: 'Wonka',
    vote_average: 7.2,
    vote_count: 3450,
    duration: 116,
    situation: 'released',
    budget: 125000000,
    revenue: 634000000,
    profit: 509000000,
    sinopsis:
      'The story will focus specifically on a young Willy Wonka and how he met the Oompa-Loompas on one of his earliest adventures.',
    genre: 'Family, Fantasy, Comedy',
  },
  {
    popularity: 7.1,
    release_date: '2024-08-09',
    title: 'Alien: Romulus',
    original_title: 'Alien: Romulus',
    vote_average: 7.3,
    vote_count: 1980,
    duration: 119,
    situation: 'released',
    budget: 80000000,
    revenue: 350000000,
    profit: 270000000,
    sinopsis:
      'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    genre: 'Horror, Science Fiction, Thriller',
  },
  {
    popularity: 9.1,
    release_date: '2025-11-07',
    title: 'Superman: Legacy',
    original_title: 'Superman: Legacy',
    vote_average: 0,
    vote_count: 0,
    duration: 0,
    situation: 'upcoming',
    budget: 364000000,
    revenue: 0,
    profit: 0,
    sinopsis:
      'Superman, a humanoid alien from the planet Krypton, works as a journalist in Metropolis while using his extraordinary powers to protect the city and its citizens.',
    genre: 'Action, Adventure, Science Fiction',
  },
  {
    popularity: 5.8,
    release_date: '2023-08-18',
    title: 'Blue Beetle',
    original_title: 'Blue Beetle',
    vote_average: 6.7,
    vote_count: 2120,
    duration: 127,
    situation: 'released',
    budget: 104000000,
    revenue: 130000000,
    profit: 26000000,
    sinopsis:
      'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
    genre: 'Action, Science Fiction, Adventure',
  },
  {
    popularity: 8.7,
    release_date: '2024-11-22',
    title: 'Wicked',
    original_title: 'Wicked',
    vote_average: 7.8,
    vote_count: 3890,
    duration: 160,
    situation: 'released',
    budget: 150000000,
    revenue: 634000000,
    profit: 484000000,
    sinopsis:
      'Elphaba, a misunderstood young woman because of her green skin, and Glinda, a popular girl, become friends at Shiz University in the Land of Oz. After an encounter with the Wonderful Wizard of Oz, their friendship reaches a crossroads.',
    genre: 'Fantasy, Musical, Romance',
  },
  {
    popularity: 6.2,
    release_date: '2024-04-05',
    title: 'Ghostbusters: Frozen Empire',
    original_title: 'Ghostbusters: Frozen Empire',
    vote_average: 6.5,
    vote_count: 2670,
    duration: 115,
    situation: 'released',
    budget: 100000000,
    revenue: 201000000,
    profit: 101000000,
    sinopsis:
      'The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters. When an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home.',
    genre: 'Fantasy, Adventure, Comedy',
  },
  {
    popularity: 7.9,
    release_date: '2024-09-06',
    title: 'Beetlejuice Beetlejuice',
    original_title: 'Beetlejuice Beetlejuice',
    vote_average: 7.2,
    vote_count: 3120,
    duration: 104,
    situation: 'released',
    budget: 100000000,
    revenue: 451000000,
    profit: 351000000,
    sinopsis:
      "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
    genre: 'Comedy, Fantasy, Horror',
  },
  {
    popularity: 5.5,
    release_date: '2023-10-20',
    title: 'Killers of the Flower Moon',
    original_title: 'Killers of the Flower Moon',
    vote_average: 7.6,
    vote_count: 2890,
    duration: 206,
    situation: 'released',
    budget: 200000000,
    revenue: 156000000,
    profit: -44000000,
    sinopsis:
      'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
    genre: 'Crime, Drama, History',
  },
  {
    popularity: 8.4,
    release_date: '2025-02-14',
    title: 'Captain America: Brave New World',
    original_title: 'Captain America: Brave New World',
    vote_average: 0,
    vote_count: 0,
    duration: 0,
    situation: 'upcoming',
    budget: 350000000,
    revenue: 0,
    profit: 0,
    sinopsis:
      'After meeting with newly elected U.S. President Thaddeus Ross, Sam Wilson finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
    genre: 'Action, Adventure, Science Fiction',
  },
] as const
